title: CDT& SECOMANE
description: 2nd International Workshop on Cyber Defence Technologies and Secure Communications at the Network Edge (CDT& SECOMANE)
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
